# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ec9d52ee785087911c5fe2c243952017578d3cae8030344ca6392a84d6e6341cec3e058eab6d5cd1f1b300972403e3e37b8dec30da04075cc143557867d316f

test:
  secret_key_base: 1d47d6a172460215881f4a25bdf000c6e9fdc3482996b6977bf860ca1512936534fada033cb0d3aa560a2b203213da422e947a7c21d25ac14e1094fb79cb396a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
